Feature/login
annecaselato/helpper-origins-riott-api pull request #1
Opened 2021-11-30 13:26 UTC by annecaselato

2021-11-30 13:29 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [[RIOTT] 01 - Login dos responsáveis](https://trello.com/c/4SMQa73f/324-riott-01-login-dos-respons%C3%A1veis)

2021-12-01 23:06 UTC, ErickHelpper requested changes

2021-12-01 23:06 UTC, ErickHelpper commented on src/library/database/entity/User.ts
> +        // const bcrypt = require('bcryptjs');
Remover código comentado

2021-12-01 23:06 UTC, ErickHelpper commented on src/library/database/entity/User.ts
> +    hashPassword(): void {
faltou nível de acesso aqui

2021-12-01 23:06 UTC, ErickHelpper commented on src/modules/users/v1/controllers/AuthController.ts
> +    async authenticate(req: Request, res: Response): Promise<void> {
Faltou nível de acesso aqui

2021-12-01 23:06 UTC, ErickHelpper commented on src/modules/users/v1/controllers/AuthController.ts
> +    async authenticate(req: Request, res: Response): Promise<void> {
Não precisa ter um validator? Caso não mande o email ou a senha ja ta tratando corretamente?

2021-12-01 23:06 UTC, ErickHelpper commented on src/modules/users/v1/controllers/UserController.ts
> +    public async privateTest(req: Request, res: Response): Promise<void> {
Esqueceu de remover a rota de teste

2021-12-06 11:04 UTC, ErickHelpper approved these changes

2021-12-06 11:05 UTC, merged