Feature/tasks
annecaselato/helpper-origins-riott-api pull request #3
Opened 2021-12-05 01:46 UTC by annecaselato

2021-12-05 01:47 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Atividade: Entidade + CRUD](https://trello.com/c/Vrjt0YaI/19-atividade-entidade-crud)

2021-12-08 23:56 UTC, ErickHelpper requested changes
Verifica essa parte da regra dos 10 caracteres, se for isso mesmo só responde meu comentário lá que eu olho depois

2021-12-08 23:56 UTC, ErickHelpper commented on src/modules/tasks/v1/middlewares/TaskValidator.ts
> +                    min: 10
Porque essa regra de mínimo 10 caracteres? Pelo que olhei na estória não tem ela

2021-12-08 23:56 UTC, ErickHelpper commented on src/modules/users/v1/controllers/AuthController.ts
> +// Modules
Estranho... esse arquivo não era pra estar aparecendo aqui ja que ele ja está mergeado

2021-12-08 23:59 UTC, annecaselato commented on src/modules/tasks/v1/middlewares/TaskValidator.ts
> +                    min: 10
Não tem mesmo não, eu coloquei meio arbitrariamente

2021-12-09 22:22 UTC, ErickHelpper requested changes

2021-12-09 22:22 UTC, ErickHelpper commented on src/modules/tasks/v1/middlewares/TaskValidator.ts
> +                    min: 10
Melhor tirar então, não vejo motivo pra limitar a descrição

2021-12-10 00:09 UTC, annecaselato commented on src/modules/tasks/v1/middlewares/TaskValidator.ts
> +                    min: 10
Beleza, corrigido!

2021-12-10 00:11 UTC, ErickHelpper approved these changes
show!

2021-12-10 00:11 UTC, merged