bugfix/login
annecaselato/helpper-origins-riott-api pull request #4
Opened 2021-12-08 19:30 UTC by annecaselato

Corrige o login para retornar apenas o token.

2021-12-08 19:32 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Login: correção do retorno](https://trello.com/c/kBHhPMsD/34-login-corre%C3%A7%C3%A3o-do-retorno)

2021-12-08 23:02 UTC, ErickHelpper requested changes

2021-12-08 23:02 UTC, ErickHelpper commented on src/modules/users/v1/controllers/AuthController.ts
> +            RouteResponse.successEmpty(res.json(token));
Não tinha reparado no outro PR, sucessEmpty é usado pra respostas que não retornam dados, como aqui vai retornar o token pode utilizar apenas o success, e coloca o token dentro de um objeto com atributo token só para padronização.

2021-12-09 22:18 UTC, ErickHelpper approved these changes

2021-12-09 22:19 UTC, merged