Feature/checklist
annecaselato/helpper-origins-riott-api pull request #5
Opened 2021-12-17 22:52 UTC by annecaselato

2021-12-17 22:52 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Lista de atividades: CRUD](https://trello.com/c/pf1COXGA/21-lista-de-atividades-crud)

2021-12-18 13:32 UTC, ErickHelpper requested changes

2021-12-18 13:32 UTC, ErickHelpper commented on src/library/BaseValidator.ts
> +    public static formatDate(data: string): Date {
Não sei o que rolou com as branches mas isso aqui não deveria ir visto que foi apagado posteriormente em membros, vai ter que remover

2021-12-18 13:51 UTC, ErickHelpper approved these changes

2021-12-18 13:51 UTC, merged