Feature/history sort
annecaselato/helpper-origins-riott-api pull request #8
Opened 2021-12-20 20:46 UTC by annecaselato

2021-12-20 20:48 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar filtro de data de finalização das listas.](https://trello.com/c/0Wh6VQRB/40-criar-filtro-de-data-de-finaliza%C3%A7%C3%A3o-das-listas)

2021-12-20 22:26 UTC, ErickHelpper requested changes

2021-12-20 22:26 UTC, ErickHelpper commented on src/modules/checklists/v1/controllers/ChecklistController.ts
> +                closedLists.sort((b, a) => Number(a.closeDate) - Number(b.closeDate));
Ficou bem confuso esse b/a trocado nos parâmetros, troca ele na lógica que fica mais fácil de entender.

2021-12-20 22:31 UTC, ErickHelpper requested changes

2021-12-20 22:31 UTC, ErickHelpper commented on src/modules/checklists/v1/controllers/ChecklistController.ts
> +            listItems.forEach(async (element: ListItem) => {
forEach não pode ser assíncrono, pode usar um for of nesse caso.

quiser dar uma olhada:
https://oieduardorabelo.medium.com/javascript-armadilhas-do-asyn-await-em-loops-1cdad44db7f0

2021-12-22 17:54 UTC, ErickHelpper approved these changes

2021-12-22 17:54 UTC, merged